org: aredotna
app: dossier-url
service: dossier-url

custom:
  bucket: arena-dossier
  bundle:
    caching: false
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp && npm install --arch=x64 --platform=linux --target=10.15.0 sharp

plugins:
  - serverless-plugin-include-dependencies
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 3008
  timeout: 120
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: CloudFront caching for Dossier (${opt:stage, 'dev'})
          DefaultCacheBehavior:
            TargetOriginId: DossierOrigin
            ViewerProtocolPolicy: "redirect-to-https"
            DefaultTTL: 86400
            ForwardedValues:
              Headers:
                - x-auth-token
              QueryString: true
              QueryStringCacheKeys:
                - url
          Enabled: true
          Origins:
            - Id: DossierOrigin
              DomainName:
                Fn::Join:
                  - "."
                  - - Ref: ApiGatewayRestApi
                    - execute-api.us-east-1.amazonaws.com
              OriginPath: /${opt:stage, 'dev'}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only

functions:
  URLScreenshot:
    handler: screenshot.getURLScreenshot
    timeout: 120
    layers:
      - arn:aws:lambda:us-east-1:583577227413:layer:ChromeAwsLambda:1
    environment:
      BUCKET: ${self:custom.bucket}
      TOKEN: ${env:DOSSIER_TOKEN}
    events:
      - http:
          path: screenshot
          method: get
          cors: true
  URLMetadata:
    handler: index.getURLMetadata
    events:
      - http:
          path: metadata
          method: get
          cors: true
