org: aredotna
app: dossier-url
service: dossier-url

plugins:
  - serverless-plugin-include-dependencies
  - serverless-dotenv-plugin

functions:
  URLMetadata:
    handler: index.getURLMetadata
    events:
      - http:
          path: metadata
          method: get
          cors: true
