org: aredotna
app: dossier-url
service: dossier-url

provider:
  name: aws
  runtime: nodejs12.x

functions:
  URLMetadata:
    handler: index.getURLMetadata
    events:
      - http:
          path: metadata
          method: get
          cors: true
